
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
 name: waypoint
 namespace: istio-system 
 labels:
    istio.io/waypoint-for: all
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  annotations:
  labels:
    istio.io/use-waypoint: waypoint
  name: www.httpbin.org
  namespace: istio-system
spec:
  hosts:
  - www.httpbin.org
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: squid-httpbin-proxy
  namespace: istio-system
spec:
  hosts:
  - squid.kind
  ports:
  - name: https
    number: 3128
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-httpbin
  namespace: istio-system
spec:
  parentRefs:
  - name: www.httpbin.org
    namespace: istio-system
    kind: ServiceEntry
    group: networking.istio.io
  rules:
  - backendRefs:
    - name: squid.kind
      kind: Hostname
      port: 3128
      group: networking.istio.io
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-via-proxy
  namespace: istio-system
spec:
  host: squid.kind
  trafficPolicy:
      tunnel:
        protocol: CONNECT
        targetHost: www.httpbin.org
        targetPort: 443

