apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
data:
  squid.conf: |
    http_port 3128

    # Allow all clients
    acl all src 0.0.0.0/0
    http_access allow all

    # Logging
    access_log /var/log/squid/access.log squid

    # DNS nameservers (optional for containers)
    dns_nameservers 8.8.8.8 8.8.4.4

    # Disable caching (optional)
    cache deny all
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: sameersbn/squid:3.5.27-2
        ports:
        - containerPort: 3128
        volumeMounts:
        - name: squid-config
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
        - name: squid-cache
          mountPath: /var/spool/squid
        - name: squid-logs
          mountPath: /var/log/squid
      volumes:
      - name: squid-config
        configMap:
          name: squid-config
      - name: squid-cache
        emptyDir: {}
      - name: squid-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: squid
spec:
  selector:
    app: squid
  ports:
  - name: squid
    port: 3128
    targetPort: 3128
  type: ClusterIP
