apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: default
  # labels:
  #   sidecar.istio.io/inject: "true"
spec:
  containers:
  - image: nicolaka/netshoot
    name: shell
    command:
      - "sleep"
      - "infinity"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  volumes:
  - name: lib-modules
    hostPath:
      path: /lib/modules
