#### Create a namespace curl-client1 , enable ambient mode and run a pod in it with a specific service account

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    # istio-injection: enabled
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    istio.io/use-waypoint-namespace: istio-system
  name: curl-client1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-client1
  namespace: curl-client1

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shoot
    # istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint
    # istio.io/use-waypoint-namespace: istio-system
  name: shoot
  namespace: curl-client1
spec:
  serviceAccountName: curl-client1
  containers:
  - command:
    - sleep
    - infinity
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    name: shoot


#### Create a namespace curl-client2 , enable ambient mode with waypoint and run a pod in it with a specific service account
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    # istio-injection: enabled
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    istio.io/use-waypoint-namespace: istio-system
  name: curl-client2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-client2
  namespace: curl-client2

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shoot
    # istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint
    # istio.io/use-waypoint-namespace: istio-system
  name: shoot
  namespace: curl-client2
spec:
  serviceAccountName: curl-client2
  containers:
  - command:
    - sleep
    - infinity
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    name: shoot


#### Create a namespace curl-client3 , enable ambient mode without waypoint and run a pod in it with a specific service account
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    # istio-injection: enabled
    istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint
    # istio.io/use-waypoint-namespace: istio-system
  name: curl-client3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-client3
  namespace: curl-client3

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shoot
    # istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint
    # istio.io/use-waypoint-namespace: istio-system
  name: shoot
  namespace: curl-client3
spec:
  serviceAccountName: curl-client3
  containers:
  - command:
    - sleep
    - infinity
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    name: shoot
